services:
  - type: web
    name: mycelium-api
    env: node
    region: frankfurt
    plan: free
    buildCommand: cd server && npm install && npm run build
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: mycelium-db
          property: connectionString

databases:
  - name: mycelium-db
    databaseName: mycelium_db
    user: mycelium
    region: frankfurt
    plan: free
